// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum PacketType : byte
{
  NONE = 0,
  C_SignUp = 1,
  SD_SignUp = 2,
  SC_SignUp = 3,
  D_SignUp = 4,
  C_SignIn = 5,
  SD_SignIn = 6,
  SC_SignIn = 7,
  D_SignIn = 8,
  SC_SignOut = 9,
  C_SignOut = 10,
  C_EnterChannel = 11,
  SC_EnterChannel = 12,
  C_ChannelInfo = 13,
  SC_ChannelInfo = 14,
  C_CharacterList = 15,
  SD_CharacterList = 16,
  D_CharacterList = 17,
  SC_CharacterList = 18,
  C_CheckName = 19,
  SD_CheckName = 20,
  D_CheckName = 21,
  SC_CheckName = 22,
  C_CreateCharacter = 23,
  SD_CreateCharacter = 24,
  D_CreateCharacter = 25,
  SC_CreateCharacter = 26,
};



static public class PacketTypeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((PacketType)typeId)
    {
      case PacketType.C_SignUp:
        result = C_SignUpVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SD_SignUp:
        result = SD_SignUpVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_SignUp:
        result = SC_SignUpVerify.Verify(verifier, tablePos);
        break;
      case PacketType.D_SignUp:
        result = D_SignUpVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_SignIn:
        result = C_SignInVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SD_SignIn:
        result = SD_SignInVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_SignIn:
        result = SC_SignInVerify.Verify(verifier, tablePos);
        break;
      case PacketType.D_SignIn:
        result = D_SignInVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_SignOut:
        result = SC_SignOutVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_SignOut:
        result = C_SignOutVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_EnterChannel:
        result = C_EnterChannelVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_EnterChannel:
        result = SC_EnterChannelVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_ChannelInfo:
        result = C_ChannelInfoVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_ChannelInfo:
        result = SC_ChannelInfoVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_CharacterList:
        result = C_CharacterListVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SD_CharacterList:
        result = SD_CharacterListVerify.Verify(verifier, tablePos);
        break;
      case PacketType.D_CharacterList:
        result = D_CharacterListVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_CharacterList:
        result = SC_CharacterListVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_CheckName:
        result = C_CheckNameVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SD_CheckName:
        result = SD_CheckNameVerify.Verify(verifier, tablePos);
        break;
      case PacketType.D_CheckName:
        result = D_CheckNameVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_CheckName:
        result = SC_CheckNameVerify.Verify(verifier, tablePos);
        break;
      case PacketType.C_CreateCharacter:
        result = C_CreateCharacterVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SD_CreateCharacter:
        result = SD_CreateCharacterVerify.Verify(verifier, tablePos);
        break;
      case PacketType.D_CreateCharacter:
        result = D_CreateCharacterVerify.Verify(verifier, tablePos);
        break;
      case PacketType.SC_CreateCharacter:
        result = SC_CreateCharacterVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

