// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOVE_H_
#define FLATBUFFERS_GENERATED_MOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

struct C_MoveStart;
struct C_MoveStartBuilder;

struct SC_MoveStart;
struct SC_MoveStartBuilder;

struct C_MoveEnd;
struct C_MoveEndBuilder;

struct SC_MoveEnd;
struct SC_MoveEndBuilder;

struct C_Jump;
struct C_JumpBuilder;

struct SC_Jump;
struct SC_JumpBuilder;

struct C_ProneStabStart;
struct C_ProneStabStartBuilder;

struct SC_ProneStabStart;
struct SC_ProneStabStartBuilder;

struct C_ProneStabEnd;
struct C_ProneStabEndBuilder;

struct SC_ProneStabEnd;
struct SC_ProneStabEndBuilder;

enum MoveDirection : uint8_t {
  MoveDirection_NONE = 0,
  MoveDirection_LEFT = 1,
  MoveDirection_RIGHT = 2,
  MoveDirection_UP = 3,
  MoveDirection_DOWN = 4,
  MoveDirection_MIN = MoveDirection_NONE,
  MoveDirection_MAX = MoveDirection_DOWN
};

inline const MoveDirection (&EnumValuesMoveDirection())[5] {
  static const MoveDirection values[] = {
    MoveDirection_NONE,
    MoveDirection_LEFT,
    MoveDirection_RIGHT,
    MoveDirection_UP,
    MoveDirection_DOWN
  };
  return values;
}

inline const char * const *EnumNamesMoveDirection() {
  static const char * const names[6] = {
    "NONE",
    "LEFT",
    "RIGHT",
    "UP",
    "DOWN",
    nullptr
  };
  return names;
}

inline const char *EnumNameMoveDirection(MoveDirection e) {
  if (::flatbuffers::IsOutRange(e, MoveDirection_NONE, MoveDirection_DOWN)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMoveDirection()[index];
}

struct C_MoveStart FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C_MoveStartBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIR = 4,
    VT_X = 6,
    VT_Y = 8
  };
  MoveDirection dir() const {
    return static_cast<MoveDirection>(GetField<uint8_t>(VT_DIR, 0));
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DIR, 1) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           verifier.EndTable();
  }
};

struct C_MoveStartBuilder {
  typedef C_MoveStart Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dir(MoveDirection dir) {
    fbb_.AddElement<uint8_t>(C_MoveStart::VT_DIR, static_cast<uint8_t>(dir), 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(C_MoveStart::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(C_MoveStart::VT_Y, y, 0.0f);
  }
  explicit C_MoveStartBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C_MoveStart> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C_MoveStart>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C_MoveStart> CreateC_MoveStart(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    MoveDirection dir = MoveDirection_NONE,
    float x = 0.0f,
    float y = 0.0f) {
  C_MoveStartBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_dir(dir);
  return builder_.Finish();
}

struct SC_MoveStart FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_MoveStartBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DIR = 6,
    VT_X = 8,
    VT_Y = 10
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  MoveDirection dir() const {
    return static_cast<MoveDirection>(GetField<uint8_t>(VT_DIR, 0));
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_DIR, 1) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           verifier.EndTable();
  }
};

struct SC_MoveStartBuilder {
  typedef SC_MoveStart Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(SC_MoveStart::VT_ID, id, 0);
  }
  void add_dir(MoveDirection dir) {
    fbb_.AddElement<uint8_t>(SC_MoveStart::VT_DIR, static_cast<uint8_t>(dir), 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(SC_MoveStart::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(SC_MoveStart::VT_Y, y, 0.0f);
  }
  explicit SC_MoveStartBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_MoveStart> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_MoveStart>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_MoveStart> CreateSC_MoveStart(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    MoveDirection dir = MoveDirection_NONE,
    float x = 0.0f,
    float y = 0.0f) {
  SC_MoveStartBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_dir(dir);
  return builder_.Finish();
}

struct C_MoveEnd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C_MoveEndBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           verifier.EndTable();
  }
};

struct C_MoveEndBuilder {
  typedef C_MoveEnd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(C_MoveEnd::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(C_MoveEnd::VT_Y, y, 0.0f);
  }
  explicit C_MoveEndBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C_MoveEnd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C_MoveEnd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C_MoveEnd> CreateC_MoveEnd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f) {
  C_MoveEndBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct SC_MoveEnd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_MoveEndBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_X = 6,
    VT_Y = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           verifier.EndTable();
  }
};

struct SC_MoveEndBuilder {
  typedef SC_MoveEnd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(SC_MoveEnd::VT_ID, id, 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(SC_MoveEnd::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(SC_MoveEnd::VT_Y, y, 0.0f);
  }
  explicit SC_MoveEndBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_MoveEnd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_MoveEnd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_MoveEnd> CreateSC_MoveEnd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    float x = 0.0f,
    float y = 0.0f) {
  SC_MoveEndBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct C_Jump FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C_JumpBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct C_JumpBuilder {
  typedef C_Jump Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit C_JumpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C_Jump> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C_Jump>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C_Jump> CreateC_Jump(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  C_JumpBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SC_Jump FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_JumpBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           verifier.EndTable();
  }
};

struct SC_JumpBuilder {
  typedef SC_Jump Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(SC_Jump::VT_ID, id, 0);
  }
  explicit SC_JumpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_Jump> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_Jump>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_Jump> CreateSC_Jump(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0) {
  SC_JumpBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct C_ProneStabStart FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C_ProneStabStartBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct C_ProneStabStartBuilder {
  typedef C_ProneStabStart Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit C_ProneStabStartBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C_ProneStabStart> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C_ProneStabStart>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C_ProneStabStart> CreateC_ProneStabStart(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  C_ProneStabStartBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SC_ProneStabStart FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_ProneStabStartBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           verifier.EndTable();
  }
};

struct SC_ProneStabStartBuilder {
  typedef SC_ProneStabStart Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(SC_ProneStabStart::VT_ID, id, 0);
  }
  explicit SC_ProneStabStartBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_ProneStabStart> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_ProneStabStart>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_ProneStabStart> CreateSC_ProneStabStart(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0) {
  SC_ProneStabStartBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct C_ProneStabEnd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C_ProneStabEndBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct C_ProneStabEndBuilder {
  typedef C_ProneStabEnd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit C_ProneStabEndBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C_ProneStabEnd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C_ProneStabEnd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C_ProneStabEnd> CreateC_ProneStabEnd(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  C_ProneStabEndBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SC_ProneStabEnd FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SC_ProneStabEndBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           verifier.EndTable();
  }
};

struct SC_ProneStabEndBuilder {
  typedef SC_ProneStabEnd Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(SC_ProneStabEnd::VT_ID, id, 0);
  }
  explicit SC_ProneStabEndBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SC_ProneStabEnd> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SC_ProneStabEnd>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SC_ProneStabEnd> CreateSC_ProneStabEnd(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0) {
  SC_ProneStabEndBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_MOVE_H_
