// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "CharacterSelect_generated.h"
#include "CreateCharacter_generated.h"
#include "Login_generated.h"
#include "Move_generated.h"
#include "Spawn_generated.h"
#include "WorldSelect_generated.h"

enum PacketType : uint8_t {
  PacketType_NONE = 0,
  PacketType_C_SignUp = 1,
  PacketType_SD_SignUp = 2,
  PacketType_SC_SignUp = 3,
  PacketType_D_SignUp = 4,
  PacketType_C_SignIn = 5,
  PacketType_SD_SignIn = 6,
  PacketType_SC_SignIn = 7,
  PacketType_D_SignIn = 8,
  PacketType_C_EnterChannel = 9,
  PacketType_SC_EnterChannel = 10,
  PacketType_C_ChannelInfo = 11,
  PacketType_SC_ChannelInfo = 12,
  PacketType_C_CharacterList = 13,
  PacketType_SD_CharacterList = 14,
  PacketType_D_CharacterList = 15,
  PacketType_SC_CharacterList = 16,
  PacketType_C_CharacterDelete = 17,
  PacketType_SD_CharacterDelete = 18,
  PacketType_D_CharacterDelete = 19,
  PacketType_SC_CharacterDelete = 20,
  PacketType_C_CharacterSelect = 21,
  PacketType_SD_CharacterSelect = 22,
  PacketType_D_CharacterSelect = 23,
  PacketType_SC_CharacterSelect = 24,
  PacketType_C_CheckName = 25,
  PacketType_SD_CheckName = 26,
  PacketType_D_CheckName = 27,
  PacketType_SC_CheckName = 28,
  PacketType_C_CreateCharacter = 29,
  PacketType_SD_CreateCharacter = 30,
  PacketType_D_CreateCharacter = 31,
  PacketType_SC_CreateCharacter = 32,
  PacketType_C_EnterMap = 33,
  PacketType_SC_EnterMap = 34,
  PacketType_C_EnterGame = 35,
  PacketType_SC_PSpawn = 36,
  PacketType_SC_MSpawn = 37,
  PacketType_C_Despawn = 38,
  PacketType_SC_Despawn = 39,
  PacketType_C_CreatureInfos = 40,
  PacketType_SC_CreatureInfos = 41,
  PacketType_C_MoveStart = 42,
  PacketType_SC_MoveStart = 43,
  PacketType_C_MoveEnd = 44,
  PacketType_SC_MoveEnd = 45,
  PacketType_C_Jump = 46,
  PacketType_SC_Jump = 47,
  PacketType_C_ProneStabStart = 48,
  PacketType_SC_ProneStabStart = 49,
  PacketType_C_ProneStabEnd = 50,
  PacketType_SC_ProneStabEnd = 51,
  PacketType_MIN = PacketType_NONE,
  PacketType_MAX = PacketType_SC_ProneStabEnd
};

inline const PacketType (&EnumValuesPacketType())[52] {
  static const PacketType values[] = {
    PacketType_NONE,
    PacketType_C_SignUp,
    PacketType_SD_SignUp,
    PacketType_SC_SignUp,
    PacketType_D_SignUp,
    PacketType_C_SignIn,
    PacketType_SD_SignIn,
    PacketType_SC_SignIn,
    PacketType_D_SignIn,
    PacketType_C_EnterChannel,
    PacketType_SC_EnterChannel,
    PacketType_C_ChannelInfo,
    PacketType_SC_ChannelInfo,
    PacketType_C_CharacterList,
    PacketType_SD_CharacterList,
    PacketType_D_CharacterList,
    PacketType_SC_CharacterList,
    PacketType_C_CharacterDelete,
    PacketType_SD_CharacterDelete,
    PacketType_D_CharacterDelete,
    PacketType_SC_CharacterDelete,
    PacketType_C_CharacterSelect,
    PacketType_SD_CharacterSelect,
    PacketType_D_CharacterSelect,
    PacketType_SC_CharacterSelect,
    PacketType_C_CheckName,
    PacketType_SD_CheckName,
    PacketType_D_CheckName,
    PacketType_SC_CheckName,
    PacketType_C_CreateCharacter,
    PacketType_SD_CreateCharacter,
    PacketType_D_CreateCharacter,
    PacketType_SC_CreateCharacter,
    PacketType_C_EnterMap,
    PacketType_SC_EnterMap,
    PacketType_C_EnterGame,
    PacketType_SC_PSpawn,
    PacketType_SC_MSpawn,
    PacketType_C_Despawn,
    PacketType_SC_Despawn,
    PacketType_C_CreatureInfos,
    PacketType_SC_CreatureInfos,
    PacketType_C_MoveStart,
    PacketType_SC_MoveStart,
    PacketType_C_MoveEnd,
    PacketType_SC_MoveEnd,
    PacketType_C_Jump,
    PacketType_SC_Jump,
    PacketType_C_ProneStabStart,
    PacketType_SC_ProneStabStart,
    PacketType_C_ProneStabEnd,
    PacketType_SC_ProneStabEnd
  };
  return values;
}

inline const char * const *EnumNamesPacketType() {
  static const char * const names[53] = {
    "NONE",
    "C_SignUp",
    "SD_SignUp",
    "SC_SignUp",
    "D_SignUp",
    "C_SignIn",
    "SD_SignIn",
    "SC_SignIn",
    "D_SignIn",
    "C_EnterChannel",
    "SC_EnterChannel",
    "C_ChannelInfo",
    "SC_ChannelInfo",
    "C_CharacterList",
    "SD_CharacterList",
    "D_CharacterList",
    "SC_CharacterList",
    "C_CharacterDelete",
    "SD_CharacterDelete",
    "D_CharacterDelete",
    "SC_CharacterDelete",
    "C_CharacterSelect",
    "SD_CharacterSelect",
    "D_CharacterSelect",
    "SC_CharacterSelect",
    "C_CheckName",
    "SD_CheckName",
    "D_CheckName",
    "SC_CheckName",
    "C_CreateCharacter",
    "SD_CreateCharacter",
    "D_CreateCharacter",
    "SC_CreateCharacter",
    "C_EnterMap",
    "SC_EnterMap",
    "C_EnterGame",
    "SC_PSpawn",
    "SC_MSpawn",
    "C_Despawn",
    "SC_Despawn",
    "C_CreatureInfos",
    "SC_CreatureInfos",
    "C_MoveStart",
    "SC_MoveStart",
    "C_MoveEnd",
    "SC_MoveEnd",
    "C_Jump",
    "SC_Jump",
    "C_ProneStabStart",
    "SC_ProneStabStart",
    "C_ProneStabEnd",
    "SC_ProneStabEnd",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketType(PacketType e) {
  if (::flatbuffers::IsOutRange(e, PacketType_NONE, PacketType_SC_ProneStabEnd)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketType()[index];
}

template<typename T> struct PacketTypeTraits {
  static const PacketType enum_value = PacketType_NONE;
};

template<> struct PacketTypeTraits<C_SignUp> {
  static const PacketType enum_value = PacketType_C_SignUp;
};

template<> struct PacketTypeTraits<SD_SignUp> {
  static const PacketType enum_value = PacketType_SD_SignUp;
};

template<> struct PacketTypeTraits<SC_SignUp> {
  static const PacketType enum_value = PacketType_SC_SignUp;
};

template<> struct PacketTypeTraits<D_SignUp> {
  static const PacketType enum_value = PacketType_D_SignUp;
};

template<> struct PacketTypeTraits<C_SignIn> {
  static const PacketType enum_value = PacketType_C_SignIn;
};

template<> struct PacketTypeTraits<SD_SignIn> {
  static const PacketType enum_value = PacketType_SD_SignIn;
};

template<> struct PacketTypeTraits<SC_SignIn> {
  static const PacketType enum_value = PacketType_SC_SignIn;
};

template<> struct PacketTypeTraits<D_SignIn> {
  static const PacketType enum_value = PacketType_D_SignIn;
};

template<> struct PacketTypeTraits<C_EnterChannel> {
  static const PacketType enum_value = PacketType_C_EnterChannel;
};

template<> struct PacketTypeTraits<SC_EnterChannel> {
  static const PacketType enum_value = PacketType_SC_EnterChannel;
};

template<> struct PacketTypeTraits<C_ChannelInfo> {
  static const PacketType enum_value = PacketType_C_ChannelInfo;
};

template<> struct PacketTypeTraits<SC_ChannelInfo> {
  static const PacketType enum_value = PacketType_SC_ChannelInfo;
};

template<> struct PacketTypeTraits<C_CharacterList> {
  static const PacketType enum_value = PacketType_C_CharacterList;
};

template<> struct PacketTypeTraits<SD_CharacterList> {
  static const PacketType enum_value = PacketType_SD_CharacterList;
};

template<> struct PacketTypeTraits<D_CharacterList> {
  static const PacketType enum_value = PacketType_D_CharacterList;
};

template<> struct PacketTypeTraits<SC_CharacterList> {
  static const PacketType enum_value = PacketType_SC_CharacterList;
};

template<> struct PacketTypeTraits<C_CharacterDelete> {
  static const PacketType enum_value = PacketType_C_CharacterDelete;
};

template<> struct PacketTypeTraits<SD_CharacterDelete> {
  static const PacketType enum_value = PacketType_SD_CharacterDelete;
};

template<> struct PacketTypeTraits<D_CharacterDelete> {
  static const PacketType enum_value = PacketType_D_CharacterDelete;
};

template<> struct PacketTypeTraits<SC_CharacterDelete> {
  static const PacketType enum_value = PacketType_SC_CharacterDelete;
};

template<> struct PacketTypeTraits<C_CharacterSelect> {
  static const PacketType enum_value = PacketType_C_CharacterSelect;
};

template<> struct PacketTypeTraits<SD_CharacterSelect> {
  static const PacketType enum_value = PacketType_SD_CharacterSelect;
};

template<> struct PacketTypeTraits<D_CharacterSelect> {
  static const PacketType enum_value = PacketType_D_CharacterSelect;
};

template<> struct PacketTypeTraits<SC_CharacterSelect> {
  static const PacketType enum_value = PacketType_SC_CharacterSelect;
};

template<> struct PacketTypeTraits<C_CheckName> {
  static const PacketType enum_value = PacketType_C_CheckName;
};

template<> struct PacketTypeTraits<SD_CheckName> {
  static const PacketType enum_value = PacketType_SD_CheckName;
};

template<> struct PacketTypeTraits<D_CheckName> {
  static const PacketType enum_value = PacketType_D_CheckName;
};

template<> struct PacketTypeTraits<SC_CheckName> {
  static const PacketType enum_value = PacketType_SC_CheckName;
};

template<> struct PacketTypeTraits<C_CreateCharacter> {
  static const PacketType enum_value = PacketType_C_CreateCharacter;
};

template<> struct PacketTypeTraits<SD_CreateCharacter> {
  static const PacketType enum_value = PacketType_SD_CreateCharacter;
};

template<> struct PacketTypeTraits<D_CreateCharacter> {
  static const PacketType enum_value = PacketType_D_CreateCharacter;
};

template<> struct PacketTypeTraits<SC_CreateCharacter> {
  static const PacketType enum_value = PacketType_SC_CreateCharacter;
};

template<> struct PacketTypeTraits<C_EnterMap> {
  static const PacketType enum_value = PacketType_C_EnterMap;
};

template<> struct PacketTypeTraits<SC_EnterMap> {
  static const PacketType enum_value = PacketType_SC_EnterMap;
};

template<> struct PacketTypeTraits<C_EnterGame> {
  static const PacketType enum_value = PacketType_C_EnterGame;
};

template<> struct PacketTypeTraits<SC_PSpawn> {
  static const PacketType enum_value = PacketType_SC_PSpawn;
};

template<> struct PacketTypeTraits<SC_MSpawn> {
  static const PacketType enum_value = PacketType_SC_MSpawn;
};

template<> struct PacketTypeTraits<C_Despawn> {
  static const PacketType enum_value = PacketType_C_Despawn;
};

template<> struct PacketTypeTraits<SC_Despawn> {
  static const PacketType enum_value = PacketType_SC_Despawn;
};

template<> struct PacketTypeTraits<C_CreatureInfos> {
  static const PacketType enum_value = PacketType_C_CreatureInfos;
};

template<> struct PacketTypeTraits<SC_CreatureInfos> {
  static const PacketType enum_value = PacketType_SC_CreatureInfos;
};

template<> struct PacketTypeTraits<C_MoveStart> {
  static const PacketType enum_value = PacketType_C_MoveStart;
};

template<> struct PacketTypeTraits<SC_MoveStart> {
  static const PacketType enum_value = PacketType_SC_MoveStart;
};

template<> struct PacketTypeTraits<C_MoveEnd> {
  static const PacketType enum_value = PacketType_C_MoveEnd;
};

template<> struct PacketTypeTraits<SC_MoveEnd> {
  static const PacketType enum_value = PacketType_SC_MoveEnd;
};

template<> struct PacketTypeTraits<C_Jump> {
  static const PacketType enum_value = PacketType_C_Jump;
};

template<> struct PacketTypeTraits<SC_Jump> {
  static const PacketType enum_value = PacketType_SC_Jump;
};

template<> struct PacketTypeTraits<C_ProneStabStart> {
  static const PacketType enum_value = PacketType_C_ProneStabStart;
};

template<> struct PacketTypeTraits<SC_ProneStabStart> {
  static const PacketType enum_value = PacketType_SC_ProneStabStart;
};

template<> struct PacketTypeTraits<C_ProneStabEnd> {
  static const PacketType enum_value = PacketType_C_ProneStabEnd;
};

template<> struct PacketTypeTraits<SC_ProneStabEnd> {
  static const PacketType enum_value = PacketType_SC_ProneStabEnd;
};

bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type);
bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

inline bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type) {
  switch (type) {
    case PacketType_NONE: {
      return true;
    }
    case PacketType_C_SignUp: {
      auto ptr = reinterpret_cast<const C_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_SignUp: {
      auto ptr = reinterpret_cast<const SD_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SignUp: {
      auto ptr = reinterpret_cast<const SC_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_SignUp: {
      auto ptr = reinterpret_cast<const D_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_SignIn: {
      auto ptr = reinterpret_cast<const C_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_SignIn: {
      auto ptr = reinterpret_cast<const SD_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SignIn: {
      auto ptr = reinterpret_cast<const SC_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_SignIn: {
      auto ptr = reinterpret_cast<const D_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_EnterChannel: {
      auto ptr = reinterpret_cast<const C_EnterChannel *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_EnterChannel: {
      auto ptr = reinterpret_cast<const SC_EnterChannel *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_ChannelInfo: {
      auto ptr = reinterpret_cast<const C_ChannelInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_ChannelInfo: {
      auto ptr = reinterpret_cast<const SC_ChannelInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CharacterList: {
      auto ptr = reinterpret_cast<const C_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CharacterList: {
      auto ptr = reinterpret_cast<const SD_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CharacterList: {
      auto ptr = reinterpret_cast<const D_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CharacterList: {
      auto ptr = reinterpret_cast<const SC_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CharacterDelete: {
      auto ptr = reinterpret_cast<const C_CharacterDelete *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CharacterDelete: {
      auto ptr = reinterpret_cast<const SD_CharacterDelete *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CharacterDelete: {
      auto ptr = reinterpret_cast<const D_CharacterDelete *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CharacterDelete: {
      auto ptr = reinterpret_cast<const SC_CharacterDelete *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CharacterSelect: {
      auto ptr = reinterpret_cast<const C_CharacterSelect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CharacterSelect: {
      auto ptr = reinterpret_cast<const SD_CharacterSelect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CharacterSelect: {
      auto ptr = reinterpret_cast<const D_CharacterSelect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CharacterSelect: {
      auto ptr = reinterpret_cast<const SC_CharacterSelect *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CheckName: {
      auto ptr = reinterpret_cast<const C_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CheckName: {
      auto ptr = reinterpret_cast<const SD_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CheckName: {
      auto ptr = reinterpret_cast<const D_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CheckName: {
      auto ptr = reinterpret_cast<const SC_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CreateCharacter: {
      auto ptr = reinterpret_cast<const C_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CreateCharacter: {
      auto ptr = reinterpret_cast<const SD_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CreateCharacter: {
      auto ptr = reinterpret_cast<const D_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CreateCharacter: {
      auto ptr = reinterpret_cast<const SC_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_EnterMap: {
      auto ptr = reinterpret_cast<const C_EnterMap *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_EnterMap: {
      auto ptr = reinterpret_cast<const SC_EnterMap *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_EnterGame: {
      auto ptr = reinterpret_cast<const C_EnterGame *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_PSpawn: {
      auto ptr = reinterpret_cast<const SC_PSpawn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_MSpawn: {
      auto ptr = reinterpret_cast<const SC_MSpawn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_Despawn: {
      auto ptr = reinterpret_cast<const C_Despawn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_Despawn: {
      auto ptr = reinterpret_cast<const SC_Despawn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CreatureInfos: {
      auto ptr = reinterpret_cast<const C_CreatureInfos *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CreatureInfos: {
      auto ptr = reinterpret_cast<const SC_CreatureInfos *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_MoveStart: {
      auto ptr = reinterpret_cast<const C_MoveStart *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_MoveStart: {
      auto ptr = reinterpret_cast<const SC_MoveStart *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_MoveEnd: {
      auto ptr = reinterpret_cast<const C_MoveEnd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_MoveEnd: {
      auto ptr = reinterpret_cast<const SC_MoveEnd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_Jump: {
      auto ptr = reinterpret_cast<const C_Jump *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_Jump: {
      auto ptr = reinterpret_cast<const SC_Jump *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_ProneStabStart: {
      auto ptr = reinterpret_cast<const C_ProneStabStart *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_ProneStabStart: {
      auto ptr = reinterpret_cast<const SC_ProneStabStart *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_ProneStabEnd: {
      auto ptr = reinterpret_cast<const C_ProneStabEnd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_ProneStabEnd: {
      auto ptr = reinterpret_cast<const SC_ProneStabEnd *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketType(
        verifier,  values->Get(i), types->GetEnum<PacketType>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
