// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_CharacterDelete : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static C_CharacterDelete GetRootAsC_CharacterDelete(ByteBuffer _bb) { return GetRootAsC_CharacterDelete(_bb, new C_CharacterDelete()); }
  public static C_CharacterDelete GetRootAsC_CharacterDelete(ByteBuffer _bb, C_CharacterDelete obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_CharacterDelete __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong CharId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<C_CharacterDelete> CreateC_CharacterDelete(FlatBufferBuilder builder,
      ulong char_id = 0) {
    builder.StartTable(1);
    C_CharacterDelete.AddCharId(builder, char_id);
    return C_CharacterDelete.EndC_CharacterDelete(builder);
  }

  public static void StartC_CharacterDelete(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharId(FlatBufferBuilder builder, ulong charId) { builder.AddUlong(0, charId, 0); }
  public static Offset<C_CharacterDelete> EndC_CharacterDelete(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_CharacterDelete>(o);
  }
}


static public class C_CharacterDeleteVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CharId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
