// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_MoveStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static C_MoveStart GetRootAsC_MoveStart(ByteBuffer _bb) { return GetRootAsC_MoveStart(_bb, new C_MoveStart()); }
  public static C_MoveStart GetRootAsC_MoveStart(ByteBuffer _bb, C_MoveStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_MoveStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MoveDirection Dir { get { int o = __p.__offset(4); return o != 0 ? (MoveDirection)__p.bb.Get(o + __p.bb_pos) : MoveDirection.NONE; } }
  public float X { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<C_MoveStart> CreateC_MoveStart(FlatBufferBuilder builder,
      MoveDirection dir = MoveDirection.NONE,
      float x = 0.0f,
      float y = 0.0f) {
    builder.StartTable(3);
    C_MoveStart.AddY(builder, y);
    C_MoveStart.AddX(builder, x);
    C_MoveStart.AddDir(builder, dir);
    return C_MoveStart.EndC_MoveStart(builder);
  }

  public static void StartC_MoveStart(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddDir(FlatBufferBuilder builder, MoveDirection dir) { builder.AddByte(0, (byte)dir, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(1, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(2, y, 0.0f); }
  public static Offset<C_MoveStart> EndC_MoveStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_MoveStart>(o);
  }
}


static public class C_MoveStartVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Dir*/, 1 /*MoveDirection*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*X*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Y*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
