// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_Portal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static C_Portal GetRootAsC_Portal(ByteBuffer _bb) { return GetRootAsC_Portal(_bb, new C_Portal()); }
  public static C_Portal GetRootAsC_Portal(ByteBuffer _bb, C_Portal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_Portal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte PortalId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<C_Portal> CreateC_Portal(FlatBufferBuilder builder,
      byte portal_id = 0) {
    builder.StartTable(1);
    C_Portal.AddPortalId(builder, portal_id);
    return C_Portal.EndC_Portal(builder);
  }

  public static void StartC_Portal(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPortalId(FlatBufferBuilder builder, byte portalId) { builder.AddByte(0, portalId, 0); }
  public static Offset<C_Portal> EndC_Portal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_Portal>(o);
  }
}


static public class C_PortalVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PortalId*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
