// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_ProneStabStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static C_ProneStabStart GetRootAsC_ProneStabStart(ByteBuffer _bb) { return GetRootAsC_ProneStabStart(_bb, new C_ProneStabStart()); }
  public static C_ProneStabStart GetRootAsC_ProneStabStart(ByteBuffer _bb, C_ProneStabStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_ProneStabStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartC_ProneStabStart(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<C_ProneStabStart> EndC_ProneStabStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_ProneStabStart>(o);
  }
}


static public class C_ProneStabStartVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}
