// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C_UpdatePosition : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static C_UpdatePosition GetRootAsC_UpdatePosition(ByteBuffer _bb) { return GetRootAsC_UpdatePosition(_bb, new C_UpdatePosition()); }
  public static C_UpdatePosition GetRootAsC_UpdatePosition(ByteBuffer _bb, C_UpdatePosition obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C_UpdatePosition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Position? Position { get { int o = __p.__offset(4); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<C_UpdatePosition> CreateC_UpdatePosition(FlatBufferBuilder builder,
      Offset<Position> positionOffset = default(Offset<Position>)) {
    builder.StartTable(1);
    C_UpdatePosition.AddPosition(builder, positionOffset);
    return C_UpdatePosition.EndC_UpdatePosition(builder);
  }

  public static void StartC_UpdatePosition(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(0, positionOffset.Value, 0); }
  public static Offset<C_UpdatePosition> EndC_UpdatePosition(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<C_UpdatePosition>(o);
  }
}


static public class C_UpdatePositionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Position*/, PositionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
