// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterTotalInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static CharacterTotalInfo GetRootAsCharacterTotalInfo(ByteBuffer _bb) { return GetRootAsCharacterTotalInfo(_bb, new CharacterTotalInfo()); }
  public static CharacterTotalInfo GetRootAsCharacterTotalInfo(ByteBuffer _bb, CharacterTotalInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterTotalInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CharacterPreviewInfo? PrevInfo { get { int o = __p.__offset(4); return o != 0 ? (CharacterPreviewInfo?)(new CharacterPreviewInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string LastPos { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLastPosBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetLastPosBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetLastPosArray() { return __p.__vector_as_array<byte>(6); }
  public int Hp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Mp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Exp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CharacterTotalInfo> CreateCharacterTotalInfo(FlatBufferBuilder builder,
      Offset<CharacterPreviewInfo> prev_infoOffset = default(Offset<CharacterPreviewInfo>),
      StringOffset last_posOffset = default(StringOffset),
      int hp = 0,
      int mp = 0,
      int exp = 0) {
    builder.StartTable(5);
    CharacterTotalInfo.AddExp(builder, exp);
    CharacterTotalInfo.AddMp(builder, mp);
    CharacterTotalInfo.AddHp(builder, hp);
    CharacterTotalInfo.AddLastPos(builder, last_posOffset);
    CharacterTotalInfo.AddPrevInfo(builder, prev_infoOffset);
    return CharacterTotalInfo.EndCharacterTotalInfo(builder);
  }

  public static void StartCharacterTotalInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddPrevInfo(FlatBufferBuilder builder, Offset<CharacterPreviewInfo> prevInfoOffset) { builder.AddOffset(0, prevInfoOffset.Value, 0); }
  public static void AddLastPos(FlatBufferBuilder builder, StringOffset lastPosOffset) { builder.AddOffset(1, lastPosOffset.Value, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(2, hp, 0); }
  public static void AddMp(FlatBufferBuilder builder, int mp) { builder.AddInt(3, mp, 0); }
  public static void AddExp(FlatBufferBuilder builder, int exp) { builder.AddInt(4, exp, 0); }
  public static Offset<CharacterTotalInfo> EndCharacterTotalInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CharacterTotalInfo>(o);
  }
}


static public class CharacterTotalInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*PrevInfo*/, CharacterPreviewInfoVerify.Verify, false)
      && verifier.VerifyString(tablePos, 6 /*LastPos*/, false)
      && verifier.VerifyField(tablePos, 8 /*Hp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Mp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Exp*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
