// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum CheckNameError : byte
{
  SUCCESS = 0,
  OVERLAPEED = 1,
  UNKNOWN = 2,
};

