// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Coin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Coin GetRootAsCoin(ByteBuffer _bb) { return GetRootAsCoin(_bb, new Coin()); }
  public static Coin GetRootAsCoin(ByteBuffer _bb, Coin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Coin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ushort Money { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public float X { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Coin> CreateCoin(FlatBufferBuilder builder,
      ulong id = 0,
      ushort money = 0,
      float x = 0.0f,
      float y = 0.0f) {
    builder.StartTable(4);
    Coin.AddId(builder, id);
    Coin.AddY(builder, y);
    Coin.AddX(builder, x);
    Coin.AddMoney(builder, money);
    return Coin.EndCoin(builder);
  }

  public static void StartCoin(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddMoney(FlatBufferBuilder builder, ushort money) { builder.AddUshort(1, money, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(2, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(3, y, 0.0f); }
  public static Offset<Coin> EndCoin(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Coin>(o);
  }
}


static public class CoinVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Money*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*X*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Y*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
