// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum CreateCharacterError : byte
{
  SUCCESS = 0,
  OVERLAPPED = 1,
  UNKNOWN = 2,
};

