// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum CreateCharacterError : ushort
{
  SUCCESS = 0,
  FULL = 1,
  UNKNOWN = 2,
};

