// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum CreateCharacterError : byte
{
  SUCCESS = 0,
  FULL = 1,
  OVERLAPPED = 2,
  UNKNOWN = 3,
};

