// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct D_CreateCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static D_CreateCharacter GetRootAsD_CreateCharacter(ByteBuffer _bb) { return GetRootAsD_CreateCharacter(_bb, new D_CreateCharacter()); }
  public static D_CreateCharacter GetRootAsD_CreateCharacter(ByteBuffer _bb, D_CreateCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public D_CreateCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong SessionId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public CreateCharacterError Ok { get { int o = __p.__offset(6); return o != 0 ? (CreateCharacterError)__p.bb.Get(o + __p.bb_pos) : CreateCharacterError.SUCCESS; } }

  public static Offset<D_CreateCharacter> CreateD_CreateCharacter(FlatBufferBuilder builder,
      ulong session_id = 0,
      CreateCharacterError ok = CreateCharacterError.SUCCESS) {
    builder.StartTable(2);
    D_CreateCharacter.AddSessionId(builder, session_id);
    D_CreateCharacter.AddOk(builder, ok);
    return D_CreateCharacter.EndD_CreateCharacter(builder);
  }

  public static void StartD_CreateCharacter(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSessionId(FlatBufferBuilder builder, ulong sessionId) { builder.AddUlong(0, sessionId, 0); }
  public static void AddOk(FlatBufferBuilder builder, CreateCharacterError ok) { builder.AddByte(1, (byte)ok, 0); }
  public static Offset<D_CreateCharacter> EndD_CreateCharacter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<D_CreateCharacter>(o);
  }
}


static public class D_CreateCharacterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SessionId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Ok*/, 1 /*CreateCharacterError*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
