// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct D_Login : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static D_Login GetRootAsD_Login(ByteBuffer _bb) { return GetRootAsD_Login(_bb, new D_Login()); }
  public static D_Login GetRootAsD_Login(ByteBuffer _bb, D_Login obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public D_Login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Ok { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<D_Login> CreateD_Login(FlatBufferBuilder builder,
      bool ok = false) {
    builder.StartTable(1);
    D_Login.AddOk(builder, ok);
    return D_Login.EndD_Login(builder);
  }

  public static void StartD_Login(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOk(FlatBufferBuilder builder, bool ok) { builder.AddBool(0, ok, false); }
  public static Offset<D_Login> EndD_Login(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<D_Login>(o);
  }
}


static public class D_LoginVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ok*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
