// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MonsterInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static MonsterInfo GetRootAsMonsterInfo(ByteBuffer _bb) { return GetRootAsMonsterInfo(_bb, new MonsterInfo()); }
  public static MonsterInfo GetRootAsMonsterInfo(ByteBuffer _bb, MonsterInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MonsterInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Type { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ulong Id { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public Position? Position { get { int o = __p.__offset(8); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<MonsterInfo> CreateMonsterInfo(FlatBufferBuilder builder,
      byte type = 0,
      ulong id = 0,
      Offset<Position> positionOffset = default(Offset<Position>)) {
    builder.StartTable(3);
    MonsterInfo.AddId(builder, id);
    MonsterInfo.AddPosition(builder, positionOffset);
    MonsterInfo.AddType(builder, type);
    return MonsterInfo.EndMonsterInfo(builder);
  }

  public static void StartMonsterInfo(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddType(FlatBufferBuilder builder, byte type) { builder.AddByte(0, type, 0); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(1, id, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(2, positionOffset.Value, 0); }
  public static Offset<MonsterInfo> EndMonsterInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MonsterInfo>(o);
  }
}


static public class MonsterInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Type*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTable(tablePos, 8 /*Position*/, PositionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
