// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MonsterInfoDetail : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static MonsterInfoDetail GetRootAsMonsterInfoDetail(ByteBuffer _bb) { return GetRootAsMonsterInfoDetail(_bb, new MonsterInfoDetail()); }
  public static MonsterInfoDetail GetRootAsMonsterInfoDetail(ByteBuffer _bb, MonsterInfoDetail obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MonsterInfoDetail __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Type { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public Position? Position { get { int o = __p.__offset(6); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public MonsterInfo? BaseInfo { get { int o = __p.__offset(8); return o != 0 ? (MonsterInfo?)(new MonsterInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<MonsterInfoDetail> CreateMonsterInfoDetail(FlatBufferBuilder builder,
      byte type = 0,
      Offset<Position> positionOffset = default(Offset<Position>),
      Offset<MonsterInfo> base_infoOffset = default(Offset<MonsterInfo>)) {
    builder.StartTable(3);
    MonsterInfoDetail.AddBaseInfo(builder, base_infoOffset);
    MonsterInfoDetail.AddPosition(builder, positionOffset);
    MonsterInfoDetail.AddType(builder, type);
    return MonsterInfoDetail.EndMonsterInfoDetail(builder);
  }

  public static void StartMonsterInfoDetail(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddType(FlatBufferBuilder builder, byte type) { builder.AddByte(0, type, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(1, positionOffset.Value, 0); }
  public static void AddBaseInfo(FlatBufferBuilder builder, Offset<MonsterInfo> baseInfoOffset) { builder.AddOffset(2, baseInfoOffset.Value, 0); }
  public static Offset<MonsterInfoDetail> EndMonsterInfoDetail(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<MonsterInfoDetail>(o);
  }
}


static public class MonsterInfoDetailVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Type*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTable(tablePos, 6 /*Position*/, PositionVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*BaseInfo*/, MonsterInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
