// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_Attack : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_Attack GetRootAsSC_Attack(ByteBuffer _bb) { return GetRootAsSC_Attack(_bb, new SC_Attack()); }
  public static SC_Attack GetRootAsSC_Attack(ByteBuffer _bb, SC_Attack obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_Attack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public AttackEnum AttackId { get { int o = __p.__offset(6); return o != 0 ? (AttackEnum)__p.bb.Get(o + __p.bb_pos) : AttackEnum.TANJIRO_ATTACK1; } }

  public static Offset<SC_Attack> CreateSC_Attack(FlatBufferBuilder builder,
      ulong id = 0,
      AttackEnum attack_id = AttackEnum.TANJIRO_ATTACK1) {
    builder.StartTable(2);
    SC_Attack.AddId(builder, id);
    SC_Attack.AddAttackId(builder, attack_id);
    return SC_Attack.EndSC_Attack(builder);
  }

  public static void StartSC_Attack(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddAttackId(FlatBufferBuilder builder, AttackEnum attackId) { builder.AddByte(1, (byte)attackId, 0); }
  public static Offset<SC_Attack> EndSC_Attack(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_Attack>(o);
  }
}


static public class SC_AttackVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*AttackId*/, 1 /*AttackEnum*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
