// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_CheckName : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_CheckName GetRootAsSC_CheckName(ByteBuffer _bb) { return GetRootAsSC_CheckName(_bb, new SC_CheckName()); }
  public static SC_CheckName GetRootAsSC_CheckName(ByteBuffer _bb, SC_CheckName obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_CheckName __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CheckNameError Ok { get { int o = __p.__offset(4); return o != 0 ? (CheckNameError)__p.bb.Get(o + __p.bb_pos) : CheckNameError.SUCCESS; } }

  public static Offset<SC_CheckName> CreateSC_CheckName(FlatBufferBuilder builder,
      CheckNameError ok = CheckNameError.SUCCESS) {
    builder.StartTable(1);
    SC_CheckName.AddOk(builder, ok);
    return SC_CheckName.EndSC_CheckName(builder);
  }

  public static void StartSC_CheckName(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOk(FlatBufferBuilder builder, CheckNameError ok) { builder.AddByte(0, (byte)ok, 0); }
  public static Offset<SC_CheckName> EndSC_CheckName(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_CheckName>(o);
  }
}


static public class SC_CheckNameVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ok*/, 1 /*CheckNameError*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
