// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_CollectCoin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_CollectCoin GetRootAsSC_CollectCoin(ByteBuffer _bb) { return GetRootAsSC_CollectCoin(_bb, new SC_CollectCoin()); }
  public static SC_CollectCoin GetRootAsSC_CollectCoin(ByteBuffer _bb, SC_CollectCoin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_CollectCoin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong Owner { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SC_CollectCoin> CreateSC_CollectCoin(FlatBufferBuilder builder,
      ulong id = 0,
      ulong owner = 0) {
    builder.StartTable(2);
    SC_CollectCoin.AddOwner(builder, owner);
    SC_CollectCoin.AddId(builder, id);
    return SC_CollectCoin.EndSC_CollectCoin(builder);
  }

  public static void StartSC_CollectCoin(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddOwner(FlatBufferBuilder builder, ulong owner) { builder.AddUlong(1, owner, 0); }
  public static Offset<SC_CollectCoin> EndSC_CollectCoin(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_CollectCoin>(o);
  }
}


static public class SC_CollectCoinVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Owner*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
