// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_CharacterSelect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_CharacterSelect GetRootAsSC_CharacterSelect(ByteBuffer _bb) { return GetRootAsSC_CharacterSelect(_bb, new SC_CharacterSelect()); }
  public static SC_CharacterSelect GetRootAsSC_CharacterSelect(ByteBuffer _bb, SC_CharacterSelect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_CharacterSelect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CharacterTotalInfo? CharInfo { get { int o = __p.__offset(4); return o != 0 ? (CharacterTotalInfo?)(new CharacterTotalInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SC_CharacterSelect> CreateSC_CharacterSelect(FlatBufferBuilder builder,
      Offset<CharacterTotalInfo> char_infoOffset = default(Offset<CharacterTotalInfo>)) {
    builder.StartTable(1);
    SC_CharacterSelect.AddCharInfo(builder, char_infoOffset);
    return SC_CharacterSelect.EndSC_CharacterSelect(builder);
  }

  public static void StartSC_CharacterSelect(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharInfo(FlatBufferBuilder builder, Offset<CharacterTotalInfo> charInfoOffset) { builder.AddOffset(0, charInfoOffset.Value, 0); }
  public static Offset<SC_CharacterSelect> EndSC_CharacterSelect(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_CharacterSelect>(o);
  }
}


static public class SC_CharacterSelectVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*CharInfo*/, CharacterTotalInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
