// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_EnterMap : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_EnterMap GetRootAsSC_EnterMap(ByteBuffer _bb) { return GetRootAsSC_EnterMap(_bb, new SC_EnterMap()); }
  public static SC_EnterMap GetRootAsSC_EnterMap(ByteBuffer _bb, SC_EnterMap obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_EnterMap __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte MapId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public CharacterTotalInfo? MyPlayerInfo { get { int o = __p.__offset(6); return o != 0 ? (CharacterTotalInfo?)(new CharacterTotalInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SC_EnterMap> CreateSC_EnterMap(FlatBufferBuilder builder,
      byte map_id = 0,
      Offset<CharacterTotalInfo> my_player_infoOffset = default(Offset<CharacterTotalInfo>)) {
    builder.StartTable(2);
    SC_EnterMap.AddMyPlayerInfo(builder, my_player_infoOffset);
    SC_EnterMap.AddMapId(builder, map_id);
    return SC_EnterMap.EndSC_EnterMap(builder);
  }

  public static void StartSC_EnterMap(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMapId(FlatBufferBuilder builder, byte mapId) { builder.AddByte(0, mapId, 0); }
  public static void AddMyPlayerInfo(FlatBufferBuilder builder, Offset<CharacterTotalInfo> myPlayerInfoOffset) { builder.AddOffset(1, myPlayerInfoOffset.Value, 0); }
  public static Offset<SC_EnterMap> EndSC_EnterMap(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_EnterMap>(o);
  }
}


static public class SC_EnterMapVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MapId*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTable(tablePos, 6 /*MyPlayerInfo*/, CharacterTotalInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
