// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_EnterMap : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_EnterMap GetRootAsSC_EnterMap(ByteBuffer _bb) { return GetRootAsSC_EnterMap(_bb, new SC_EnterMap()); }
  public static SC_EnterMap GetRootAsSC_EnterMap(ByteBuffer _bb, SC_EnterMap obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_EnterMap __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CharacterPreviewInfo? Characters(int j) { int o = __p.__offset(4); return o != 0 ? (CharacterPreviewInfo?)(new CharacterPreviewInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CharactersLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SC_EnterMap> CreateSC_EnterMap(FlatBufferBuilder builder,
      VectorOffset charactersOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SC_EnterMap.AddCharacters(builder, charactersOffset);
    return SC_EnterMap.EndSC_EnterMap(builder);
  }

  public static void StartSC_EnterMap(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharacters(FlatBufferBuilder builder, VectorOffset charactersOffset) { builder.AddOffset(0, charactersOffset.Value, 0); }
  public static VectorOffset CreateCharactersVector(FlatBufferBuilder builder, Offset<CharacterPreviewInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCharactersVectorBlock(FlatBufferBuilder builder, Offset<CharacterPreviewInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCharactersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<CharacterPreviewInfo>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCharactersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<CharacterPreviewInfo>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCharactersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SC_EnterMap> EndSC_EnterMap(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_EnterMap>(o);
  }
}


static public class SC_EnterMapVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Characters*/, CharacterPreviewInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
