// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_HitByMonster : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_HitByMonster GetRootAsSC_HitByMonster(ByteBuffer _bb) { return GetRootAsSC_HitByMonster(_bb, new SC_HitByMonster()); }
  public static SC_HitByMonster GetRootAsSC_HitByMonster(ByteBuffer _bb, SC_HitByMonster obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_HitByMonster __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Hp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SC_HitByMonster> CreateSC_HitByMonster(FlatBufferBuilder builder,
      int hp = 0) {
    builder.StartTable(1);
    SC_HitByMonster.AddHp(builder, hp);
    return SC_HitByMonster.EndSC_HitByMonster(builder);
  }

  public static void StartSC_HitByMonster(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(0, hp, 0); }
  public static Offset<SC_HitByMonster> EndSC_HitByMonster(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_HitByMonster>(o);
  }
}


static public class SC_HitByMonsterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Hp*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
