// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_Jump : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_Jump GetRootAsSC_Jump(ByteBuffer _bb) { return GetRootAsSC_Jump(_bb, new SC_Jump()); }
  public static SC_Jump GetRootAsSC_Jump(ByteBuffer _bb, SC_Jump obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_Jump __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SC_Jump> CreateSC_Jump(FlatBufferBuilder builder,
      ulong id = 0) {
    builder.StartTable(1);
    SC_Jump.AddId(builder, id);
    return SC_Jump.EndSC_Jump(builder);
  }

  public static void StartSC_Jump(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static Offset<SC_Jump> EndSC_Jump(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_Jump>(o);
  }
}


static public class SC_JumpVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
