// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_MoveEnd : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_MoveEnd GetRootAsSC_MoveEnd(ByteBuffer _bb) { return GetRootAsSC_MoveEnd(_bb, new SC_MoveEnd()); }
  public static SC_MoveEnd GetRootAsSC_MoveEnd(ByteBuffer _bb, SC_MoveEnd obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_MoveEnd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public float X { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<SC_MoveEnd> CreateSC_MoveEnd(FlatBufferBuilder builder,
      ulong id = 0,
      float x = 0.0f,
      float y = 0.0f) {
    builder.StartTable(3);
    SC_MoveEnd.AddId(builder, id);
    SC_MoveEnd.AddY(builder, y);
    SC_MoveEnd.AddX(builder, x);
    return SC_MoveEnd.EndSC_MoveEnd(builder);
  }

  public static void StartSC_MoveEnd(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(1, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(2, y, 0.0f); }
  public static Offset<SC_MoveEnd> EndSC_MoveEnd(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_MoveEnd>(o);
  }
}


static public class SC_MoveEndVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*X*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Y*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
