// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_Portal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_Portal GetRootAsSC_Portal(ByteBuffer _bb) { return GetRootAsSC_Portal(_bb, new SC_Portal()); }
  public static SC_Portal GetRootAsSC_Portal(ByteBuffer _bb, SC_Portal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_Portal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte MapId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public CharacterInfoDetail? MyPlayerInfo { get { int o = __p.__offset(6); return o != 0 ? (CharacterInfoDetail?)(new CharacterInfoDetail()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Position? Position { get { int o = __p.__offset(8); return o != 0 ? (Position?)(new Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SC_Portal> CreateSC_Portal(FlatBufferBuilder builder,
      byte map_id = 0,
      Offset<CharacterInfoDetail> my_player_infoOffset = default(Offset<CharacterInfoDetail>),
      Offset<Position> positionOffset = default(Offset<Position>)) {
    builder.StartTable(3);
    SC_Portal.AddPosition(builder, positionOffset);
    SC_Portal.AddMyPlayerInfo(builder, my_player_infoOffset);
    SC_Portal.AddMapId(builder, map_id);
    return SC_Portal.EndSC_Portal(builder);
  }

  public static void StartSC_Portal(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddMapId(FlatBufferBuilder builder, byte mapId) { builder.AddByte(0, mapId, 0); }
  public static void AddMyPlayerInfo(FlatBufferBuilder builder, Offset<CharacterInfoDetail> myPlayerInfoOffset) { builder.AddOffset(1, myPlayerInfoOffset.Value, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<Position> positionOffset) { builder.AddOffset(2, positionOffset.Value, 0); }
  public static Offset<SC_Portal> EndSC_Portal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_Portal>(o);
  }
}


static public class SC_PortalVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MapId*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTable(tablePos, 6 /*MyPlayerInfo*/, CharacterInfoDetailVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Position*/, PositionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
