// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_Spawn : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_Spawn GetRootAsSC_Spawn(ByteBuffer _bb) { return GetRootAsSC_Spawn(_bb, new SC_Spawn()); }
  public static SC_Spawn GetRootAsSC_Spawn(ByteBuffer _bb, SC_Spawn obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_Spawn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public CharacterPreviewInfo? SpawnInfo { get { int o = __p.__offset(4); return o != 0 ? (CharacterPreviewInfo?)(new CharacterPreviewInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<SC_Spawn> CreateSC_Spawn(FlatBufferBuilder builder,
      Offset<CharacterPreviewInfo> spawn_infoOffset = default(Offset<CharacterPreviewInfo>)) {
    builder.StartTable(1);
    SC_Spawn.AddSpawnInfo(builder, spawn_infoOffset);
    return SC_Spawn.EndSC_Spawn(builder);
  }

  public static void StartSC_Spawn(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddSpawnInfo(FlatBufferBuilder builder, Offset<CharacterPreviewInfo> spawnInfoOffset) { builder.AddOffset(0, spawnInfoOffset.Value, 0); }
  public static Offset<SC_Spawn> EndSC_Spawn(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_Spawn>(o);
  }
}


static public class SC_SpawnVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*SpawnInfo*/, CharacterPreviewInfoVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
