// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_SignOut : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_SignOut GetRootAsSC_SignOut(ByteBuffer _bb) { return GetRootAsSC_SignOut(_bb, new SC_SignOut()); }
  public static SC_SignOut GetRootAsSC_SignOut(ByteBuffer _bb, SC_SignOut obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_SignOut __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSC_SignOut(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SC_SignOut> EndSC_SignOut(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_SignOut>(o);
  }
}


static public class SC_SignOutVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}
