// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_SignUp : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_SignUp GetRootAsSC_SignUp(ByteBuffer _bb) { return GetRootAsSC_SignUp(_bb, new SC_SignUp()); }
  public static SC_SignUp GetRootAsSC_SignUp(ByteBuffer _bb, SC_SignUp obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_SignUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SignUpError Ok { get { int o = __p.__offset(4); return o != 0 ? (SignUpError)__p.bb.GetUshort(o + __p.bb_pos) : SignUpError.SUCCESS; } }

  public static Offset<SC_SignUp> CreateSC_SignUp(FlatBufferBuilder builder,
      SignUpError ok = SignUpError.SUCCESS) {
    builder.StartTable(1);
    SC_SignUp.AddOk(builder, ok);
    return SC_SignUp.EndSC_SignUp(builder);
  }

  public static void StartSC_SignUp(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOk(FlatBufferBuilder builder, SignUpError ok) { builder.AddUshort(0, (ushort)ok, 0); }
  public static Offset<SC_SignUp> EndSC_SignUp(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_SignUp>(o);
  }
}


static public class SC_SignUpVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ok*/, 2 /*SignUpError*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
