// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_SignIn : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SC_SignIn GetRootAsSC_SignIn(ByteBuffer _bb) { return GetRootAsSC_SignIn(_bb, new SC_SignIn()); }
  public static SC_SignIn GetRootAsSC_SignIn(ByteBuffer _bb, SC_SignIn obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_SignIn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SignInError Ok { get { int o = __p.__offset(4); return o != 0 ? (SignInError)__p.bb.GetUshort(o + __p.bb_pos) : SignInError.SUCCESS; } }

  public static Offset<SC_SignIn> CreateSC_SignIn(FlatBufferBuilder builder,
      SignInError ok = SignInError.SUCCESS) {
    builder.StartTable(1);
    SC_SignIn.AddOk(builder, ok);
    return SC_SignIn.EndSC_SignIn(builder);
  }

  public static void StartSC_SignIn(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOk(FlatBufferBuilder builder, SignInError ok) { builder.AddUshort(0, (ushort)ok, 0); }
  public static Offset<SC_SignIn> EndSC_SignIn(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_SignIn>(o);
  }
}


static public class SC_SignInVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ok*/, 2 /*SignInError*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
