// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SD_CharacterList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SD_CharacterList GetRootAsSD_CharacterList(ByteBuffer _bb) { return GetRootAsSD_CharacterList(_bb, new SD_CharacterList()); }
  public static SD_CharacterList GetRootAsSD_CharacterList(ByteBuffer _bb, SD_CharacterList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SD_CharacterList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong SessionId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong DbId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public byte ServerId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<SD_CharacterList> CreateSD_CharacterList(FlatBufferBuilder builder,
      ulong session_id = 0,
      ulong db_id = 0,
      byte server_id = 0) {
    builder.StartTable(3);
    SD_CharacterList.AddDbId(builder, db_id);
    SD_CharacterList.AddSessionId(builder, session_id);
    SD_CharacterList.AddServerId(builder, server_id);
    return SD_CharacterList.EndSD_CharacterList(builder);
  }

  public static void StartSD_CharacterList(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSessionId(FlatBufferBuilder builder, ulong sessionId) { builder.AddUlong(0, sessionId, 0); }
  public static void AddDbId(FlatBufferBuilder builder, ulong dbId) { builder.AddUlong(1, dbId, 0); }
  public static void AddServerId(FlatBufferBuilder builder, byte serverId) { builder.AddByte(2, serverId, 0); }
  public static Offset<SD_CharacterList> EndSD_CharacterList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SD_CharacterList>(o);
  }
}


static public class SD_CharacterListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SessionId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*DbId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*ServerId*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
