// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SD_CreateCharacter : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SD_CreateCharacter GetRootAsSD_CreateCharacter(ByteBuffer _bb) { return GetRootAsSD_CreateCharacter(_bb, new SD_CreateCharacter()); }
  public static SD_CreateCharacter GetRootAsSD_CreateCharacter(ByteBuffer _bb, SD_CreateCharacter obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SD_CreateCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong DbId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong SessionId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ushort CharId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<SD_CreateCharacter> CreateSD_CreateCharacter(FlatBufferBuilder builder,
      ulong db_id = 0,
      ulong session_id = 0,
      ushort char_id = 0) {
    builder.StartTable(3);
    SD_CreateCharacter.AddSessionId(builder, session_id);
    SD_CreateCharacter.AddDbId(builder, db_id);
    SD_CreateCharacter.AddCharId(builder, char_id);
    return SD_CreateCharacter.EndSD_CreateCharacter(builder);
  }

  public static void StartSD_CreateCharacter(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddDbId(FlatBufferBuilder builder, ulong dbId) { builder.AddUlong(0, dbId, 0); }
  public static void AddSessionId(FlatBufferBuilder builder, ulong sessionId) { builder.AddUlong(1, sessionId, 0); }
  public static void AddCharId(FlatBufferBuilder builder, ushort charId) { builder.AddUshort(2, charId, 0); }
  public static Offset<SD_CreateCharacter> EndSD_CreateCharacter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SD_CreateCharacter>(o);
  }
}


static public class SD_CreateCharacterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*DbId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SessionId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*CharId*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
