// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SD_CheckName : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SD_CheckName GetRootAsSD_CheckName(ByteBuffer _bb) { return GetRootAsSD_CheckName(_bb, new SD_CheckName()); }
  public static SD_CheckName GetRootAsSD_CheckName(ByteBuffer _bb, SD_CheckName obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SD_CheckName __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong SessionId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<SD_CheckName> CreateSD_CheckName(FlatBufferBuilder builder,
      ulong session_id = 0,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(2);
    SD_CheckName.AddSessionId(builder, session_id);
    SD_CheckName.AddName(builder, nameOffset);
    return SD_CheckName.EndSD_CheckName(builder);
  }

  public static void StartSD_CheckName(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSessionId(FlatBufferBuilder builder, ulong sessionId) { builder.AddUlong(0, sessionId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static Offset<SD_CheckName> EndSD_CheckName(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SD_CheckName>(o);
  }
}


static public class SD_CheckNameVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SessionId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
