// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SD_SignUp : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SD_SignUp GetRootAsSD_SignUp(ByteBuffer _bb) { return GetRootAsSD_SignUp(_bb, new SD_SignUp()); }
  public static SD_SignUp GetRootAsSD_SignUp(ByteBuffer _bb, SD_SignUp obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SD_SignUp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string UserId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUserIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUserIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUserIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Passowrd { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPassowrdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPassowrdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPassowrdArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<SD_SignUp> CreateSD_SignUp(FlatBufferBuilder builder,
      StringOffset user_idOffset = default(StringOffset),
      StringOffset passowrdOffset = default(StringOffset)) {
    builder.StartTable(2);
    SD_SignUp.AddPassowrd(builder, passowrdOffset);
    SD_SignUp.AddUserId(builder, user_idOffset);
    return SD_SignUp.EndSD_SignUp(builder);
  }

  public static void StartSD_SignUp(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUserId(FlatBufferBuilder builder, StringOffset userIdOffset) { builder.AddOffset(0, userIdOffset.Value, 0); }
  public static void AddPassowrd(FlatBufferBuilder builder, StringOffset passowrdOffset) { builder.AddOffset(1, passowrdOffset.Value, 0); }
  public static Offset<SD_SignUp> EndSD_SignUp(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SD_SignUp>(o);
  }
}


static public class SD_SignUpVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*UserId*/, false)
      && verifier.VerifyString(tablePos, 6 /*Passowrd*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
