// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum SignUpError : ushort
{
  SUCCESS = 0,
  OVERLAPPED_USERID = 1,
  UNKNOWN = 2,
};

