// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum SignInError : ushort
{
  SUCCESS = 0,
  INVALID_ID = 1,
  INVALID_PW = 2,
  UNKNOWN = 3,
};

