// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Tanjiro_Attack : byte
{
  SwingT2 = 0,
  Swing = 1,
  SwingT1 = 2,
  SwingT3 = 3,
};

