// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "CharacterSelect_generated.h"
#include "CreateCharacter_generated.h"
#include "Login_generated.h"
#include "WorldSelect_generated.h"

enum PacketType : uint8_t {
  PacketType_NONE = 0,
  PacketType_C_SignUp = 1,
  PacketType_SD_SignUp = 2,
  PacketType_SC_SignUp = 3,
  PacketType_D_SignUp = 4,
  PacketType_C_SignIn = 5,
  PacketType_SD_SignIn = 6,
  PacketType_SC_SignIn = 7,
  PacketType_D_SignIn = 8,
  PacketType_SC_SignOut = 9,
  PacketType_C_SignOut = 10,
  PacketType_C_EnterChannel = 11,
  PacketType_SC_EnterChannel = 12,
  PacketType_C_ChannelInfo = 13,
  PacketType_SC_ChannelInfo = 14,
  PacketType_C_CharacterList = 15,
  PacketType_SD_CharacterList = 16,
  PacketType_D_CharacterList = 17,
  PacketType_SC_CharacterList = 18,
  PacketType_C_CheckName = 19,
  PacketType_SD_CheckName = 20,
  PacketType_D_CheckName = 21,
  PacketType_SC_CheckName = 22,
  PacketType_C_CreateCharacter = 23,
  PacketType_SD_CreateCharacter = 24,
  PacketType_D_CreateCharacter = 25,
  PacketType_SC_CreateCharacter = 26,
  PacketType_MIN = PacketType_NONE,
  PacketType_MAX = PacketType_SC_CreateCharacter
};

inline const PacketType (&EnumValuesPacketType())[27] {
  static const PacketType values[] = {
    PacketType_NONE,
    PacketType_C_SignUp,
    PacketType_SD_SignUp,
    PacketType_SC_SignUp,
    PacketType_D_SignUp,
    PacketType_C_SignIn,
    PacketType_SD_SignIn,
    PacketType_SC_SignIn,
    PacketType_D_SignIn,
    PacketType_SC_SignOut,
    PacketType_C_SignOut,
    PacketType_C_EnterChannel,
    PacketType_SC_EnterChannel,
    PacketType_C_ChannelInfo,
    PacketType_SC_ChannelInfo,
    PacketType_C_CharacterList,
    PacketType_SD_CharacterList,
    PacketType_D_CharacterList,
    PacketType_SC_CharacterList,
    PacketType_C_CheckName,
    PacketType_SD_CheckName,
    PacketType_D_CheckName,
    PacketType_SC_CheckName,
    PacketType_C_CreateCharacter,
    PacketType_SD_CreateCharacter,
    PacketType_D_CreateCharacter,
    PacketType_SC_CreateCharacter
  };
  return values;
}

inline const char * const *EnumNamesPacketType() {
  static const char * const names[28] = {
    "NONE",
    "C_SignUp",
    "SD_SignUp",
    "SC_SignUp",
    "D_SignUp",
    "C_SignIn",
    "SD_SignIn",
    "SC_SignIn",
    "D_SignIn",
    "SC_SignOut",
    "C_SignOut",
    "C_EnterChannel",
    "SC_EnterChannel",
    "C_ChannelInfo",
    "SC_ChannelInfo",
    "C_CharacterList",
    "SD_CharacterList",
    "D_CharacterList",
    "SC_CharacterList",
    "C_CheckName",
    "SD_CheckName",
    "D_CheckName",
    "SC_CheckName",
    "C_CreateCharacter",
    "SD_CreateCharacter",
    "D_CreateCharacter",
    "SC_CreateCharacter",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketType(PacketType e) {
  if (::flatbuffers::IsOutRange(e, PacketType_NONE, PacketType_SC_CreateCharacter)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketType()[index];
}

template<typename T> struct PacketTypeTraits {
  static const PacketType enum_value = PacketType_NONE;
};

template<> struct PacketTypeTraits<C_SignUp> {
  static const PacketType enum_value = PacketType_C_SignUp;
};

template<> struct PacketTypeTraits<SD_SignUp> {
  static const PacketType enum_value = PacketType_SD_SignUp;
};

template<> struct PacketTypeTraits<SC_SignUp> {
  static const PacketType enum_value = PacketType_SC_SignUp;
};

template<> struct PacketTypeTraits<D_SignUp> {
  static const PacketType enum_value = PacketType_D_SignUp;
};

template<> struct PacketTypeTraits<C_SignIn> {
  static const PacketType enum_value = PacketType_C_SignIn;
};

template<> struct PacketTypeTraits<SD_SignIn> {
  static const PacketType enum_value = PacketType_SD_SignIn;
};

template<> struct PacketTypeTraits<SC_SignIn> {
  static const PacketType enum_value = PacketType_SC_SignIn;
};

template<> struct PacketTypeTraits<D_SignIn> {
  static const PacketType enum_value = PacketType_D_SignIn;
};

template<> struct PacketTypeTraits<SC_SignOut> {
  static const PacketType enum_value = PacketType_SC_SignOut;
};

template<> struct PacketTypeTraits<C_SignOut> {
  static const PacketType enum_value = PacketType_C_SignOut;
};

template<> struct PacketTypeTraits<C_EnterChannel> {
  static const PacketType enum_value = PacketType_C_EnterChannel;
};

template<> struct PacketTypeTraits<SC_EnterChannel> {
  static const PacketType enum_value = PacketType_SC_EnterChannel;
};

template<> struct PacketTypeTraits<C_ChannelInfo> {
  static const PacketType enum_value = PacketType_C_ChannelInfo;
};

template<> struct PacketTypeTraits<SC_ChannelInfo> {
  static const PacketType enum_value = PacketType_SC_ChannelInfo;
};

template<> struct PacketTypeTraits<C_CharacterList> {
  static const PacketType enum_value = PacketType_C_CharacterList;
};

template<> struct PacketTypeTraits<SD_CharacterList> {
  static const PacketType enum_value = PacketType_SD_CharacterList;
};

template<> struct PacketTypeTraits<D_CharacterList> {
  static const PacketType enum_value = PacketType_D_CharacterList;
};

template<> struct PacketTypeTraits<SC_CharacterList> {
  static const PacketType enum_value = PacketType_SC_CharacterList;
};

template<> struct PacketTypeTraits<C_CheckName> {
  static const PacketType enum_value = PacketType_C_CheckName;
};

template<> struct PacketTypeTraits<SD_CheckName> {
  static const PacketType enum_value = PacketType_SD_CheckName;
};

template<> struct PacketTypeTraits<D_CheckName> {
  static const PacketType enum_value = PacketType_D_CheckName;
};

template<> struct PacketTypeTraits<SC_CheckName> {
  static const PacketType enum_value = PacketType_SC_CheckName;
};

template<> struct PacketTypeTraits<C_CreateCharacter> {
  static const PacketType enum_value = PacketType_C_CreateCharacter;
};

template<> struct PacketTypeTraits<SD_CreateCharacter> {
  static const PacketType enum_value = PacketType_SD_CreateCharacter;
};

template<> struct PacketTypeTraits<D_CreateCharacter> {
  static const PacketType enum_value = PacketType_D_CreateCharacter;
};

template<> struct PacketTypeTraits<SC_CreateCharacter> {
  static const PacketType enum_value = PacketType_SC_CreateCharacter;
};

bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type);
bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

inline bool VerifyPacketType(::flatbuffers::Verifier &verifier, const void *obj, PacketType type) {
  switch (type) {
    case PacketType_NONE: {
      return true;
    }
    case PacketType_C_SignUp: {
      auto ptr = reinterpret_cast<const C_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_SignUp: {
      auto ptr = reinterpret_cast<const SD_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SignUp: {
      auto ptr = reinterpret_cast<const SC_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_SignUp: {
      auto ptr = reinterpret_cast<const D_SignUp *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_SignIn: {
      auto ptr = reinterpret_cast<const C_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_SignIn: {
      auto ptr = reinterpret_cast<const SD_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SignIn: {
      auto ptr = reinterpret_cast<const SC_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_SignIn: {
      auto ptr = reinterpret_cast<const D_SignIn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_SignOut: {
      auto ptr = reinterpret_cast<const SC_SignOut *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_SignOut: {
      auto ptr = reinterpret_cast<const C_SignOut *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_EnterChannel: {
      auto ptr = reinterpret_cast<const C_EnterChannel *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_EnterChannel: {
      auto ptr = reinterpret_cast<const SC_EnterChannel *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_ChannelInfo: {
      auto ptr = reinterpret_cast<const C_ChannelInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_ChannelInfo: {
      auto ptr = reinterpret_cast<const SC_ChannelInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CharacterList: {
      auto ptr = reinterpret_cast<const C_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CharacterList: {
      auto ptr = reinterpret_cast<const SD_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CharacterList: {
      auto ptr = reinterpret_cast<const D_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CharacterList: {
      auto ptr = reinterpret_cast<const SC_CharacterList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CheckName: {
      auto ptr = reinterpret_cast<const C_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CheckName: {
      auto ptr = reinterpret_cast<const SD_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CheckName: {
      auto ptr = reinterpret_cast<const D_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CheckName: {
      auto ptr = reinterpret_cast<const SC_CheckName *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_C_CreateCharacter: {
      auto ptr = reinterpret_cast<const C_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SD_CreateCharacter: {
      auto ptr = reinterpret_cast<const SD_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_D_CreateCharacter: {
      auto ptr = reinterpret_cast<const D_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketType_SC_CreateCharacter: {
      auto ptr = reinterpret_cast<const SC_CreateCharacter *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketTypeVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketType(
        verifier,  values->Get(i), types->GetEnum<PacketType>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_H_
