// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum Equipment : byte
{
  NONE = 0,
  C_Monster = 1,
  S_Monster = 2,
};



static public class EquipmentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((Equipment)typeId)
    {
      case Equipment.C_Monster:
        result = C_MonsterVerify.Verify(verifier, tablePos);
        break;
      case Equipment.S_Monster:
        result = S_MonsterVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

